---
- name: configure devices
  hosts: all
  connection: local

  roles:
    - name: configure acl entries on devices
      role: acl

    - name: backup existing config to local host
      role: backup
