---
- name: configure devices
  hosts: all
  connection: local

  roles:
    - name: configure ntp services
      role: ntp

      ntp_source_interface: "{{ management_interface }}"

      ntp_servers:
        - 0.us.pool.ntp.org
        - 1.us.pool.ntp.org
        - 2.us.pool.ntp.org
        - 3.us.pool.ntp.org
