---
- name: set backup_path fact
  set_fact:
    backup_path: "{{ playbook_dir }}/backup"

- name: create backup paths
  file:
    path: "{{ backup_path }}"
    state: directory
  run_once: yes
  delegate_to: localhost

- name: create backup paths
  file:
    path: "{{ backup_path }}/{{ inventory_hostname }}"
    state: directory
  delegate_to: localhost

- name: include device specific tasks
  include: "{{ item }}"
  with_first_found:
    - files: "{{ device_os }}.yaml"
      skip: true
      paths: tasks

