---
- name: Gather All
  ios_facts:
    gather_subset: all
    provider: "{{ cli }}"

- name: Gather hardware
  ios_facts:
    gather_subset: 
    - hardware
    provider: "{{ cli }}"
 
- name: Gather interfaces
  ios_facts:
    gather_subset:
    - interfaces
    provider: "{{ cli }}"
  
- name: Gather config
  ios_facts:
    gather_subset:
    - config
    provider: "{{ cli }}"
  
- name: Gather default
  ios_facts:
    gather_subset:
    - default
    provider: "{{ cli }}"
